name: CI on GCP via Cirun

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    # Gunakan label sesuai dengan .cirun.yml
    runs-on: [self-hosted, cirun-gcp]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests in parallel (CPU-heavy)
        run: |
          pytest -n auto  # gunakan pytest-xdist untuk eksekusi paralel otomatis

      - name: Display CPU info
        run: |
          nproc && free -h && lscpu
